defmodule MyApp.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:users, primary_key: false) do
      add(:id, :binary_id, null: false, default: nil, primary_key: true)
      add(:email, :text, null: false, default: nil, primary_key: false)
    end

    create table(:tweets, primary_key: false) do
      add(:id, :binary_id, null: false, default: nil, primary_key: true)

      add(:user_id, references("users", type: :binary_id, column: :id),
        default: nil,
        primary_key: false
      )

      add(:updated_at, :utc_datetime, null: true, default: fragment("now()"), primary_key: false)
      add(:public, :boolean, null: false, default: false, primary_key: false)
      add(:created_at, :utc_datetime, null: true, default: fragment("now()"), primary_key: false)
      add(:body, :text, null: false, default: nil, primary_key: false)
    end
  end

  def down() do
    drop(table("tweets"))

    drop(table("users"))
  end
end